Feature/3 storybook 설정
mission-ui/mission-ui pull request #9
Opened 2024-09-13 05:32 UTC by bamin0422

## Issue
storybook 설정
## Description
- Storybook 설정
- theme 설정
## Check List
- [x] Source/Target Branch 확인
- [x] Assignee 설정
- [x] Reviewer 설정
- [x] Labels 설정

2024-09-13 05:37 UTC, kanghyun98 commented
프로젝트 전개 MR이랑 내용이 겹치는게 있는데 분리 해주세여

2024-09-14 08:05 UTC, kanghyun98 requested changes

2024-09-14 08:05 UTC, kanghyun98 commented on package.json
p2: 버전 캐럿 + yarn.lock 한번 확인 부탁할게여

2024-09-14 08:07 UTC, bamin0422 commented on package.json
넴넴!

2024-09-14 08:31 UTC, bamin0422 commented on package.json
반영했습니다~

2024-09-14 08:33 UTC, kanghyun98 approved these changes

2024-09-14 10:33 UTC, merged